#!/usr/bin/env python3
"""
Render the onboarding demo GIFs.

These are drawn frame by frame rather than screen-recorded, for two reasons:
a recording is stale the moment the UI changes, and it would show whatever
happened to be on the author's screen. Drawing them means they always match the
shipped design, they contain nothing personal, and they can be regenerated by
anyone with `python tools/make_demos.py`.

Everything shown is behaviour Stark actually has — the same keystroke, the same
ghost text, the same accept. Nothing here is aspirational.

Writes app/Demos/{rewrite,predict,aura}.gif, which make_app.sh copies into
Resources/demos/.
"""

import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "app", "Demos")

# Retina: render at 2x and let the app scale down, so text stays crisp.
SCALE = 2
W, H = 520 * SCALE, 150 * SCALE
FPS_MS = 55

# Light palette, matched to the onboarding window. Fixed rather than sampled:
# the GIF has to look deliberate wherever it is placed, and a demo that inverts
# with the system theme would need two sets of artwork for no real gain.
BG = (252, 252, 253)
PANEL = (244, 244, 246)
STROKE = (223, 223, 227)
TEXT = (28, 28, 30)
DIM = (110, 110, 118)
FAINT = (150, 150, 158)
ACCENT = (235, 120, 20)      # the app's amber, darkened to hold on white
KEY_IDLE = (226, 226, 231)

SF = "/System/Library/Fonts/SFNS.ttf"


def font(size, weight=None):
    f = ImageFont.truetype(SF, size * SCALE)
    if weight:
        try:
            f.set_variation_by_axes([weight])
        except Exception:
            pass
    return f


F_BODY = font(15)
F_SMALL = font(11)
F_KEY = font(10, 700)
F_BIG = font(26, 700)
F_LABEL = font(12, 600)


def frame():
    img = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(img)
    # The "field" the text lives in.
    d.rounded_rectangle([16 * SCALE, 16 * SCALE, W - 16 * SCALE, H - 42 * SCALE],
                        radius=12 * SCALE, fill=PANEL, outline=STROKE, width=SCALE)
    return img, d


def keycap(d, x, y, label, pressed=False, w=26):
    w *= SCALE
    h = 20 * SCALE
    fill = ACCENT if pressed else KEY_IDLE
    fg = (255, 255, 255) if pressed else DIM
    d.rounded_rectangle([x, y, x + w, y + h], radius=5 * SCALE, fill=fill)
    bbox = d.textbbox((0, 0), label, font=F_KEY)
    d.text((x + (w - (bbox[2] - bbox[0])) / 2, y + (h - (bbox[3] - bbox[1])) / 2 - bbox[1]),
           label, font=F_KEY, fill=fg)
    return x + w + 6 * SCALE


def caret(d, x, y, h=18):
    d.rectangle([x, y, x + 2 * SCALE, y + h * SCALE], fill=ACCENT)


def hint(d, x, text):
    d.text((x, H - 30 * SCALE), text, font=F_SMALL, fill=FAINT)


def save(frames, name, durations):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, f"{name}.gif")
    frames[0].save(path, save_all=True, append_images=frames[1:],
                   duration=durations, loop=0, optimize=True, disposal=2)
    kb = os.path.getsize(path) / 1024
    print(f"  {name}.gif — {len(frames)} frames, {kb:.0f} KB")


# --------------------------------------------------------------------------


def demo_rewrite():
    """Messy text, one keystroke, clean text in its place."""
    messy = "hey i cant beleive how fast this runs"
    clean = "Hey, I can't believe how fast this runs."
    frames, durs = [], []

    for i in range(1, len(messy) + 1):
        img, d = frame()
        d.text((32 * SCALE, 40 * SCALE), messy[:i], font=F_BODY, fill=DIM)
        caret(d, 32 * SCALE + d.textlength(messy[:i], font=F_BODY) + 2 * SCALE, 39 * SCALE)
        x = keycap(d, 32 * SCALE, H - 32 * SCALE, "⌘")
        keycap(d, x, H - 32 * SCALE, "D", w=22)
        hint(d, 100 * SCALE, "press to rewrite")
        frames.append(img); durs.append(FPS_MS)

    # Hold, then the keypress lights up.
    for pressed in (False, True, True):
        img, d = frame()
        d.text((32 * SCALE, 40 * SCALE), messy, font=F_BODY, fill=DIM)
        x = keycap(d, 32 * SCALE, H - 32 * SCALE, "⌘", pressed)
        keycap(d, x, H - 32 * SCALE, "D", pressed, w=22)
        hint(d, 100 * SCALE, "press to rewrite")
        frames.append(img); durs.append(420 if not pressed else 200)

    for i in range(0, len(clean) + 1, 3):
        img, d = frame()
        d.text((32 * SCALE, 40 * SCALE), clean[:i], font=F_BODY, fill=TEXT)
        x = keycap(d, 32 * SCALE, H - 32 * SCALE, "⌘")
        keycap(d, x, H - 32 * SCALE, "D", w=22)
        hint(d, 100 * SCALE, "rewritten in place")
        frames.append(img); durs.append(28)

    img, d = frame()
    d.text((32 * SCALE, 40 * SCALE), clean, font=F_BODY, fill=TEXT)
    x = keycap(d, 32 * SCALE, H - 32 * SCALE, "⌘")
    keycap(d, x, H - 32 * SCALE, "D", w=22)
    hint(d, 100 * SCALE, "rewritten in place")
    frames.append(img); durs.append(2000)
    save(frames, "rewrite", durs)


def demo_predict():
    """Half a sentence, a dimmed continuation, Tab folds it in."""
    typed = "hey, are you free to"
    ghost = " hop on a quick call later today?"
    frames, durs = [], []

    for i in range(1, len(typed) + 1):
        img, d = frame()
        d.text((32 * SCALE, 40 * SCALE), typed[:i], font=F_BODY, fill=TEXT)
        caret(d, 32 * SCALE + d.textlength(typed[:i], font=F_BODY) + 2 * SCALE, 39 * SCALE)
        keycap(d, 32 * SCALE, H - 32 * SCALE, "tab", w=30)
        hint(d, 74 * SCALE, "keep typing…")
        frames.append(img); durs.append(FPS_MS)

    # The suggestion arrives a word at a time, the way streaming shows it.
    words = ghost.split(" ")
    partial = ""
    for w in words:
        partial += (" " if partial or w else "") + w if w else ""
        img, d = frame()
        x0 = 32 * SCALE
        d.text((x0, 40 * SCALE), typed, font=F_BODY, fill=TEXT)
        gx = x0 + d.textlength(typed, font=F_BODY)
        d.text((gx, 40 * SCALE), partial, font=F_BODY, fill=FAINT)
        keycap(d, 32 * SCALE, H - 32 * SCALE, "tab", w=30)
        hint(d, 74 * SCALE, "press to accept")
        frames.append(img); durs.append(90)

    for pressed in (False, True, True):
        img, d = frame()
        x0 = 32 * SCALE
        d.text((x0, 40 * SCALE), typed, font=F_BODY, fill=TEXT)
        d.text((x0 + d.textlength(typed, font=F_BODY), 40 * SCALE), ghost,
               font=F_BODY, fill=FAINT)
        keycap(d, 32 * SCALE, H - 32 * SCALE, "tab", pressed, w=30)
        hint(d, 74 * SCALE, "press to accept")
        frames.append(img); durs.append(500 if not pressed else 180)

    full = typed + ghost
    img, d = frame()
    d.text((32 * SCALE, 40 * SCALE), full, font=F_BODY, fill=TEXT)
    caret(d, 32 * SCALE + d.textlength(full, font=F_BODY) + 2 * SCALE, 39 * SCALE)
    keycap(d, 32 * SCALE, H - 32 * SCALE, "tab", w=30)
    hint(d, 74 * SCALE, "accepted")
    frames.append(img); durs.append(2200)
    save(frames, "predict", durs)


def demo_aura():
    """Accepted rewrites accumulating, and staying put."""
    frames, durs = [], []
    for n in range(0, 8):
        for step in range(2):
            img, d = frame()
            d.text((32 * SCALE, 34 * SCALE), "Aura, learning your voice",
                   font=F_LABEL, fill=ACCENT)
            val = str(n)
            d.text((32 * SCALE, 54 * SCALE), val, font=F_BIG, fill=TEXT)
            wv = d.textlength(val, font=F_BIG)
            d.text((32 * SCALE + wv + 8 * SCALE, 64 * SCALE), "rewrites you kept",
                   font=F_SMALL, fill=DIM)
            d.text((32 * SCALE, H - 30 * SCALE),
                   "stored on this Mac · never uploaded", font=F_SMALL, fill=FAINT)
            frames.append(img); durs.append(90 if step == 0 else 330)
    frames[-1] = frames[-1].copy()
    durs[-1] = 2200
    save(frames, "aura", durs)


if __name__ == "__main__":
    print("rendering demo GIFs…")
    demo_rewrite()
    demo_predict()
    demo_aura()
    print(f"-> {os.path.normpath(OUT)}")
